### ISSUE TITLE
Question regarding the hyperparameters for TranSVAE

### ISSUE THREAD

**Issue by KPeng9510** [ldkong1205/TranSVAE#1]
Hey, thank you so much for your nice work!

I am currently using the TranSVAE and want to reproduce the results for UCF101 to HMDB, could you by any chance share the config file for the hyper parameters, e.g., the weights for different losses? 

Another question, did you use the checkpoints from this repo (https://github.com/piergiaj/pytorch-i3d/tree/master/models) to extract the features? Thank you!

Best regards.

KPeng

**Comment by ldkong1205** [comment]
Hi @KPeng9510, thank you for your interest in this work!

For your questions:
- We will upload the config file soon and let you know once it is ready.
- Yes, we used the I3D weights to extract the features.

Thanks again!

**Comment by KPeng9510** [comment]
Ok, thanks for your fast response!

**Comment by ldkong1205** [comment]
@KPeng9510, by the way, we have just uploaded the supplementary file, please see it [here](https://github.com/ldkong1205/TranSVAE/blob/main/asset/supp.pdf). We have included the detailed hyperparameter configurations we were using after the grid search. You can follow this file first if you don't mind. The config files will be updated later. Thanks!

**Comment by KPeng9510** [comment]
Ok nice, I will check this file:), have a nice day! Thanks!

**Comment by ldkong1205** [comment]
> Ok nice, I will check this file:), have a nice day! Thanks!

You too!
