### ISSUE TITLE
Problem with the provided notebook code

### ISSUE THREAD

**Issue by muxiddin19** [ldkong1205/TranSVAE#10]
I am facing problem with the running the provided notebook code:
if __name__ == '__main__':
    main(opt)
give the below problem:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_5944/3014985375.py in <module>
      1 if __name__ == '__main__':
----> 2     main(opt)

/tmp/ipykernel_5944/1548203155.py in main(opt)
     42 
     43     #=== Preparing model ===#
---> 44     model = TransferVAE.TranSVAE_Video(opt)
     45     #model = TransferVAE.TransferVAE_Video(opt)
     46     if not opt.parallel_train:

/mnt/e/muhiddin/transvae/exp/TransferVAE.py in __init__(self, opt)
     34         self.dropout_rate = opt.dropout_rate
     35         self.num_class = opt.num_class
---> 36         self.prior_sample = opt.prior_sample
     37 
     38         if self.input_type == 'image':

AttributeError: 'Namespace' object has no attribute 'prior_sample'

if __name__ == '__main__':
    best_prec1 = 0
    opt.src = 'ucf101'
    opt.tar = 'hmdb51'
    opt.weight_MI = 50
    opt.weight_cls = 1
    opt.weight_triplet = 1
    opt.weight_adv = 1
    opt.tar_psuedo_thre = 0.93
    opt.num_segments = 8
    main(opt)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_5944/2806786463.py in <module>
      9     opt.tar_psuedo_thre = 0.93
     10     opt.num_segments = 8
---> 11     main(opt)

/tmp/ipykernel_5944/1548203155.py in main(opt)
     42 
     43     #=== Preparing model ===#
---> 44     model = TransferVAE.TranSVAE_Video(opt)
     45     #model = TransferVAE.TransferVAE_Video(opt)
     46     if not opt.parallel_train:

/mnt/e/muhiddin/transvae/exp/TransferVAE.py in __init__(self, opt)
     34         self.dropout_rate = opt.dropout_rate
     35         self.num_class = opt.num_class
---> 36         self.prior_sample = opt.prior_sample
     37 
     38         if self.input_type == 'image':

AttributeError: 'Namespace' object has no attribute 'prior_sample'

What do you suggest to do?

**Comment by ldkong1205** [comment]
Hi @muxiddin19, please set `opt.prior_sample` to `'post'` and try run the script again. More details are at here: https://github.com/ldkong1205/TranSVAE/blob/main/exp/TranSVAE.py#L377.
