### ISSUE TITLE
Regarding dataset preparation steps

### ISSUE THREAD

**Issue by Anirudh257** [ldkong1205/TranSVAE#2]
Hi, @ldkong1205 Thanks for the excellent work. I wanted to reproduce the results on the Epic-kitchens UDA setting and setup the dataset for the same. Could you upload the relevant steps?

**Comment by ldkong1205** [comment]
Hi @Anirudh257, thanks for your interest in our work!

We will update the instructions soon and let you know once they're ready.

**Comment by Anirudh257** [comment]
Thanks for the prompt response @ldkong1205 If I am not mistaken, should it be similar to https://github.com/CVIR/CoMix#epic-kitchens?

**Comment by ldkong1205** [comment]
Hi @Anirudh257, you are correct. We followed the exact same configuration with CoMix when preparing this dataset. Please refer to their instructions first. Thanks!

**Comment by ldkong1205** [comment]
Hi @Anirudh257, We managed to store the I3D features on Google Drive, please download them based on your need:

| Dataset | Google Drive | Size |
| :-: | :-: | :-: |
| UCF101 | [download](https://drive.google.com/file/d/1mO4KbGJDX-Ez0pNAbsjlwriMuIu9UB0D/view?usp=drive_link) | 3 GB |
| HMDB51 | [download](https://drive.google.com/file/d/1mF9jhokka7tTLW9N48nVpXIy1n-RC3lm/view?usp=drive_link) | 1 GB | 
| Epic-Kitchens | [download](https://drive.google.com/file/d/1LhgNhnV6ZHg-xiMFp-xvx3ZozKqr81Pp/view?usp=drive_link) | 11 GB |
| Sprites | [download](https://drive.google.com/file/d/1LhrdjgZ_fNcXvIub85SwDkWX1jupHHgi/view?usp=drive_link) | 42 MB |

**Comment by Anirudh257** [comment]
Hi @ldkong1205 Thanks for letting me know! :)
