### ISSUE TITLE
When to release data and launch scripts

### ISSUE THREAD

**Issue by takfate** [ldkong1205/TranSVAE#3]

**Comment by ldkong1205** [comment]
Hi @takfate, thanks for your interest! Your requested materials will be available in the next few days. Stay tuned!

**Comment by takfate** [comment]
Thanks, looking forward to it~

**Comment by takfate** [comment]
Hello, I am very eager to get your code. Could you release the launch scripts and features?

**Comment by ldkong1205** [comment]
Hi @takfate, thanks for your interest!

We are still looking for a suitable source to store the I3D features, which require more than 34GB. Will the feature generation scripts be useful for your case? We can share them with you first and you can generate the features and store them locally.

**Comment by takfate** [comment]
I recommend using Zenodo for global support and Baidu Netdisk for Chinese support. In fact, I want to use your codebase on our own dataset. So I need your launch script to understand your codebase. It helps me adapt it to our work. The I3D feature is not very required for me. But if it can be accessed, it could speed up our progress.

**Comment by ldkong1205** [comment]
Hi @takfate, thanks for waiting! 

We managed to store the I3D features on Google Drive, please download them based on your need:

| Dataset | Google Drive | Size |
| :-: | :-: | :-: |
| UCF101 | [download](https://drive.google.com/file/d/1mO4KbGJDX-Ez0pNAbsjlwriMuIu9UB0D/view?usp=drive_link) | 3 GB |
| HMDB51 | [download](https://drive.google.com/file/d/1mF9jhokka7tTLW9N48nVpXIy1n-RC3lm/view?usp=drive_link) | 1 GB | 
| Epic-Kitchens | [download](https://drive.google.com/file/d/1LhgNhnV6ZHg-xiMFp-xvx3ZozKqr81Pp/view?usp=drive_link) | 11 GB |
| Sprites | [download](https://drive.google.com/file/d/1LhrdjgZ_fNcXvIub85SwDkWX1jupHHgi/view?usp=drive_link) | 42 MB |

The launch scripts will be available by tomorrow.

**Comment by ldkong1205** [comment]
Hi @takfate, the launch scripts are ready. Please refer to [GET_STARTED.md](https://github.com/ldkong1205/TranSVAE/blob/main/docs/GET_STARTED.md) for more details.
