### ISSUE TITLE
Problem with video2I3D.py file?

### ISSUE THREAD

**Issue by muxiddin19** [ldkong1205/TranSVAE#5]
Hello! I'm facing an issue with a missing file. Could you assist me with this problem?
(transvae) wsl@DESKTOP-CJL0ECN:/mnt/e/muhiddin/transvae/dataset_preparation$ ./script_video2feature.sh
python3: can't open file '/mnt/e/muhiddin/transvae/dataset_preparation/video2I3D.py': [Errno 2] No such file or directory

(transvae) wsl@DESKTOP-CJL0ECN:/mnt/e/muhiddin/transvae/dataset_preparation$ ls
README.md          pytorch_i3d.py           script_list2DA.sh           video2I3D_jester.py
dataset2split.py   script_dataset2list.sh   script_video2feature.sh     video2I3D_ucf_hmdb.py
jester_dataset.py  script_dataset2split.sh  video2I3D_epic_kitchens.py  video_dataset2list.py

Where can I get the requested video2I3D.py?

**Comment by ldkong1205** [comment]
Hi @muxiddin19, thanks for your interest in our work.

The `video2I3D` scripts are under the `TranSVAE/dataset_preparation` folder. We include separate scripts for different datasets and you can adapt the file names of them:
- [`video2I3D_epic_kitchens.py`](https://github.com/ldkong1205/TranSVAE/blob/main/dataset_preparation/video2I3D_epic_kitchens.py)
- [`video2I3D_jester.py`](https://github.com/ldkong1205/TranSVAE/blob/main/dataset_preparation/video2I3D_jester.py)
- [`video2I3D_ucf_hmdb.py`](https://github.com/ldkong1205/TranSVAE/blob/main/dataset_preparation/video2I3D_ucf_hmdb.py)
