### ISSUE TITLE
train_TransferVAE_hmdb_ucf.py ?

### ISSUE THREAD

**Issue by muxiddin19** [ldkong1205/TranSVAE#6]
Can you guide me with solving the given issue:
(transvae) wsl@DESKTOP-CJL0ECN:/mnt/e/muhiddin/transvae$ sh exp/train_script_I3D_hmdb2ucf.sh
(transvae) wsl@DESKTOP-CJL0ECN:/mnt/e/muhiddin/transvae$ python3: can't open file '/mnt/e/muhiddin/transvae/train_TransferVAE_hmdb_ucf.py': [Errno 2] No such file or directory

**Comment by ldkong1205** [comment]
Hi @muxiddin19, the training scripts are all under the `TranSVAE/exp` folder.

To use these training scripts, you can simply modify the file paths. For example, you can run the experiment on HMDB51-UCF101 using the following command:
```
python3 TranSVAE/exp/train_TransferVAE_hmdb_ucf.py \
    --src 'hmdb51' \
    --tar 'ucf101' \
    --epochs 1000 \
    --gpu 0 \
    --num_segments 9 \
    --tar_psuedo_thre 0.96 \
    --optimizer Adam \
    --lr 0.001 \
    --batch_size 128 \
    --use_psuedo 'Y' \
    --weight_MI 0.5 \
    --weight_cls 1 \
    --weight_triplet 10 \
    --weight_adv 0.1 \
    --start_psuedo_step 100 \
    --backbone 'I3Dpretrain' \
    --exp_dir 'experiments_I3D' &
```

It is also recommended to use the absolute path for running the scripts. In your case, it is just:
```
/mnt/e/muhiddin/transvae/exp/train_TransferVAE_hmdb_ucf.py
```
