### ISSUE TITLE
train_hmdb_ucf.py: error: unrecognized arguments:

### ISSUE THREAD

**Issue by muxiddin19** [ldkong1205/TranSVAE#9]
Great work! Thank you for openly publishing the code! However, I am facing a problem here. I have downloaded the related extracted features from UCF101 and HMDB datasets from the provided link in this structure:
/dataset/ucf101/I3D-feature_pretrain/...
 and
/dataset/hmdb51/I3D-feature_pretrain/...

As I have downloaded the above, there is no need to proceed with the data preparation stages.
However, there is the problem:

(transvae) gpulab2@gpulab2:~/muhiddin/TranSVAE$ sh exp/train_script_I3D_hmdb2ucf.sh
usage: train_hmdb_ucf.py [-h] [--dataset DATASET] [--data_root DATA_ROOT] [--src SRC] [--tar TAR]
                         [--input_type {feature,image}] [--seed SEED] [--exp_dir EXP_DIR]
                         [--log_indicator LOG_INDICATOR] [--model_dir MODEL_DIR]
                         [--data_threads DATA_THREADS] [--resume PATH] [--resume_hp] [--gpu GPU]
                         [--save_model SAVE_MODEL] [--parallel_train PARALLEL_TRAIN]
                         [--print_details PRINT_DETAILS] [--eval_freq EVAL_FREQ]
                         [--weighted_class_loss {Y,N}] [--weighted_class_loss_DA {Y,N}]
                         [--num_segments NUM_SEGMENTS]
                         [--backbone {dcgan,resnet101,I3Dpretrain,I3Dfinetune}]
                         [--val_segments VAL_SEGMENTS] [--channels CHANNELS] [--add_fc M]
                         [--fc_dim FC_DIM] [--frame_aggregation {rnn,trn}] [--dropout_rate DROPOUT_RATE]
                         [--f_dim F_DIM] [--z_dim Z_DIM] [--rnn_size RNN_SIZE]
                         [--f_rnn_layers F_RNN_LAYERS] [--triplet_type {mean,post}]
                         [--place_adv N [N ...]] [--use_bn {none,AdaBN,AutoDIAL}]
                         [--prior_sample {random,post}] [--optimizer {SGD,Adam}] [--epochs N]
                         [--batch_size BATCH_SIZE] [--lr LR] [--lr_decay LRDecay]
                         [--lr_adaptive {none,loss,dann}] [--lr_steps LRSteps [LRSteps ...]]
                         [--momentum M] [--weight_decay W] [--clip_gradient W] [--no_partialbn]
                         [--use_attn {none,TransAttn,general}] [--n_attn N_ATTN]
                         [--add_loss_DA {none,attentive_entropy}] [--pretrain_VAE {N,Y}]
                         [--train_TranSVAE {N,Y}] [--use_psuedo {N,Y}] [--tar_psuedo_thre W]
                         [--start_psuedo_step W] [--weight_f WEIGHT_F] [--weight_z WEIGHT_Z]
                         [--weight_MI WEIGHT_MI] [--weight_cls WEIGHT_CLS] [--beta M [M ...]]
                         [--weight_entropy WEIGHT_ENTROPY] [--weight_domain WEIGHT_DOMAIN]
                         [--weight_triplet WEIGHT_TRIPLET] [--weight_adv WEIGHT_ADV]
                         [--weight_VAE WEIGHT_VAE]
train_hmdb_ucf.py: error: unrecognized arguments:
exp/train_script_I3D_hmdb2ucf.sh: 7: exp/train_script_I3D_hmdb2ucf.sh: --src: not found

Then I tried to run directly:
(transvae) gpulab2@gpulab2:~/muhiddin/TranSVAE$ python exp/train_TransferVAE_hmdb_ucf.py

However, there is another issue, even though the beginning stage was going on:
ine 1229, in _process_data
    data.reraise()
  File "/home/gpulab2/anaconda3/envs/transvae/lib/python3.7/site-packages/torch/_utils.py", line 434, in rer
aise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/gpulab2/muhiddin/TranSVAE/exp/dataset.py", line 53, in _load_feature
    feat = [torch.load(feat_path)]
  File "/home/gpulab2/anaconda3/envs/transvae/lib/python3.7/site-packages/torch/serialization.py", line 594,
 in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/gpulab2/anaconda3/envs/transvae/lib/python3.7/site-packages/torch/serialization.py", line 230,
 in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/gpulab2/anaconda3/envs/transvae/lib/python3.7/site-packages/torch/serialization.py", line 211,
 in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/ucf101/RGB-feature/v_Punch_g16_c06/img_0003
1.t7'

During the handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gpulab2/anaconda3/envs/transvae/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py"
, line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/gpulab2/anaconda3/envs/transvae/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py",
 line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gpulab2/anaconda3/envs/transvae/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py",
 line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gpulab2/muhiddin/TranSVAE/exp/dataset.py", line 123, in __getitem__
    data_ancher, label_ancher = self.get(record, segment_indices)
  File "/home/gpulab2/muhiddin/TranSVAE/exp/dataset.py", line 151, in get
    seg_feats = self._load_feature(record.path, p)
  File "/home/gpulab2/muhiddin/TranSVAE/exp/dataset.py", line 55, in _load_feature
    print('Error loading:' % (feat_path))
TypeError: not all arguments converted during string formatting

What do you suggest for the solution?

**Comment by ldkong1205** [comment]
Hi @muxiddin19, the error seems related to the file path of your downloaded features. Please ensure your file paths do not include any unparseable symbols.
